# Generated by Django 3.0.4 on 2020-05-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
